[tool.poetry]
name = "tracking_physmed"
version = "0.1.0"
description = "Miscellaneous functions for tracking analysis in Python using DeepLabCut at Physics for Medicine"
authors = ["Felipe Cybis Pereira <felipe.cybis-pereira@espci.psl.eu>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
numpy = "^1.22.1"
pandas = "^1.3.5"
tables = "^3.7.0"
"ruamel.yaml" = "^0.17.20"
matplotlib = "^3.5.1"
opencv-python-headless = "^4.5.5"
scipy = "^1.7.3"
pytest = {version = "^7.4.4", optional = true}
ipykernel = {version = "^6.28.0", optional = true}
black = {version = "^23.12.1", optional = true}
sphinx = {version = "^5", optional = true}
sphinx-copybutton = {version = "^0.5.1", optional = true}
sphinx-design = {version = "^0.3.0", optional = true}
numpydoc = {version = "^1.5.0", optional = true}

[tool.poetry.extras]
docs = ["numpydoc", "sphinx", "sphinx-copybutton", "sphinx-design"]
test = ["pytest"]
dev = ["black", "ipykernel"]
all = [
    "numpydoc",
    "sphinx",
    "sphinx-copybutton",
    "sphinx-design",
    "pytest",
    "black",
    "ipykernel",
]

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
