[tool.poetry]
name = "tracking_physmed"
version = "0.1.0"
description = "Miscellaneous functions for tracking analysis in Python using DeepLabCut at Physics for Medicine"
authors = ["Felipe Cybis Pereira <felipe.cybis-pereira@espci.psl.eu>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
numpy = "^1.22.1"
pandas = "^1.3.5"
tables = "^3.7.0"
"ruamel.yaml" = "^0.17.20"
matplotlib = "^3.5.1"
opencv-python-headless = "^4.5.5"
scipy = "^1.7.3"

[tool.poetry.group.dev.dependencies]
pytest = "^5.2"
ipython = "^8.0.1"
ipykernel = "^6.7.0"
black = "^23"
poetry2setup = "^1.0.0"
sphinx = "^5"
furo = "^2022.12.7"
sphinx-copybutton = "^0.5.1"
sphinx-design = "^0.3.0"
numpydoc = "^1.5.0"

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
