[tool.poetry]
name = "tracking_physmed"
version = "0.1.0"
description = "Miscellaneous functions for tracking analysis in Python using DeepLabCut at Physics for Medicine"
authors = ["Felipe Cybis Pereira <felipe.cybis-pereira@espci.psl.eu>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.22.1"
pandas = "^1.3.5"
tables = "^3.7.0"
"ruamel.yaml" = "^0.17.20"
matplotlib = "^3.5.1"
opencv-python-headless = "^4.5.5"
scipy = "^1.7.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
