# Build the documentation.

name: Documentation

on:
  workflow_call:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout physbeh
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install/upgrade pip and uv
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade uv
      - name: Create virtual environment
        run: uv venv
      - name: Install dependencies
        run: uv pip install --upgrade --refresh-package physbeh --reinstall-package physbeh "physbeh[docs] @ ."
      - name: Build documentation
        run: |
          cd docs/
          # clean docs from previous run
          rm -rf build/*
          rm -rf source/auto_examples/
          rm -rf source/api/generated/
          uv run sphinx-build -b html source build
          cd ..
          rm -rf .venv/
