# This workflow runs tests and outputs coverage reports to Codecov.

name: Tests

on:
  workflow_call:
#     # Called workflows must declared which secrets will be used.
#     secrets:
#       CODECOV_TOKEN:
#         required: true

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout tracking_physmed
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install/upgrade pip and uv
        run: |
          python -m pip install --upgrade pip 
          python -m pip install --upgrade uv
      - name: Create virtual environment
        run: uv venv
      - name: Install dependencies
        run: uv pip install --upgrade --refresh-package tracking_physmed --reinstall-package tracking_physmed "tracking_physmed[test] @ ."
      - name: Test with pytest and output coverage reports (unix)
        if: ${{ ! (matrix.os == 'windows-latest') }}
        run: |
          source .venv/bin/activate
          pytest --cov=src --cov-report=xml
          deactivate
          rm -rf .venv/
      - name: Test with pytest (windows)
        if: matrix.os == 'windows-latest'
        run: |
          .venv/Scripts/activate
          pytest
          deactivate
          rm -r .venv/
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v5
      #   if: matrix.python-version == '3.11' && matrix.os == 'linux'
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     env_vars: OS,PYTHON
      #     fail_ci_if_error: true
      #     files: ./coverage.xml
      #     verbose: true
